# Generated by Django 2.0.7 on 2018-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='hii there i hope everything is gonna work fine'),
            preserve_default=False,
        ),
    ]
